language: csharp
sudo: required
mono: none
solution: Sandwych.MapMatchingKit.sln
env:
  - CLI_VERSION=latest
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
  - dotnet restore

script:
  - dotnet build src/Sandwych.Hmm -f netstandard2.0
  - dotnet build src/Sandwych.MapMatchingKit -f netstandard2.0
  - dotnet test test/Sandwych.Hmm.Tests/Sandwych.Hmm.Tests.csproj
  - dotnet test test/Sandwych.MapMatchingKit.Tests/Sandwych.MapMatchingKit.Tests.csproj
