language: csharp
mono: none
solution: Sandwych.MapMatchingKit.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test .\test\Sandwych.Hmm.Tests\Sandwych.Hmm.Tests.csproj
  - dotnet test .\test\Sandwych.MapMatchingKit.Tests\Sandwych.MapMatchingKit.Tests.csproj
