language: csharp
mono: none
dotnet: 2.0.5

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test .\test\Sandwych.Hmm.Tests\Sandwych.Hmm.Tests.csproj
  - dotnet test .\test\Sandwych.MapMatchingKit.Tests\Sandwych.MapMatchingKit.Tests.csproj
