language: csharp
mono: none
dotnet: 2.0.0
solution: Sandwych.MapMatchingKit.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

install:
  - dotnet restore

script:
  - dotnet build src/Sandwych.Hmm -r netstandard2.0
  - dotnet build src/Sandwych.MapMatchingKit -r netstandard2.0
  - dotnet test test/Sandwych.Hmm.Tests/Sandwych.Hmm.Tests.csproj
  - dotnet test test/Sandwych.MapMatchingKit.Tests/Sandwych.MapMatchingKit.Tests.csproj
