image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
build_script:
  - dotnet --version
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release .\src\Sandwych.Hmm\Sandwych.Hmm.csproj
  - dotnet pack -c Release .\src\Sandwych.MapMatchingKit\Sandwych.MapMatchingKit.csproj
test_script:
  - dotnet test .\test\Sandwych.Hmm.Tests\Sandwych.Hmm.Tests.csproj
  - dotnet test .\test\Sandwych.MapMatchingKit.Tests\Sandwych.MapMatchingKit.Tests.csproj
artifacts:
  - path: 'src\Sandwych.Hmm\**\*.nupkg'
  - path: 'src\Sandwych.MapMatchingKit\**\*.nupkg'
